version: '3.9'

services:
  minio:
    image: minio/minio:RELEASE.2023-01-20T02-05-44Z.fips
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/minio:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin@secret
    command: server --console-address ":9001" /data
    networks:
      - quack-duck-network

  elasticsearch:
    image: elasticsearch:7.17.3
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      discovery.type: single-node
      # ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
    networks:
      - quack-duck-network
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  kibana:
    image: kibana:7.17.3
    container_name: kibana
    ports:
      - 5601:5601
      - 9600:9600
    environment:
      ES_JAVA_OPTS: -Xmx512m -Xms512m
      SERVERNAME: kibana
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      ELASTICSEARCH_USERNAME: kibana_system
      # ELASTICSEARCH_PASSWORD: ${KIBANA_PASSWORD}
    networks:
      - quack-duck-network
    volumes:
      - kibana_data:/usr/share/kibana/data


networks:
  quack-duck-network:
    driver: bridge

volumes:
  elasticsearch_data:
    driver: local
  kibana_data:
    driver: local
