version: '3.9'

services:
  minio:
    image: minio/minio:RELEASE.2023-01-20T02-05-44Z.fips
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/minio:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin@secret
    command: server --console-address ":9001" /data
